---
- hosts: [appserver]
  remote_user: "{{ remote_user }}"

  tasks:
    - name: Make sure a Gunicorn service is stopped
      stat:
        path: "{{ gunicorn_service_file }}"
      register: p
    - systemd:
        state: stopped
        name: "{{ gunicorn_service_name }}"
      when: p.stat.exists

    - name: git checkout
      become: true
      become_user: "{{ app_user }}"
      git:
        repo: 'https://github.com/open-tours/backend.git'
        dest: "{{ app_dir }}"
        force: true
        version: main

    - name: Create config/.env
      become: true
      become_user: "{{ app_user }}"
      template:
        src: templates/.env.j2
        dest: "{{ app_dir }}/config/.env"

    - name: pipenv install --system
      become: true
      command: "chdir={{ app_dir }} pipenv install --system"

    - name: Run Migrations
      become: true
      become_user: "{{ app_user }}"
      command: "{{ manage_py }} migrate"

    - name: Gunicorn .service file is in place
      template:
        src: templates/gunicorn.service.j2
        dest: "{{ gunicorn_service_file }}"

    - name: Make sure a Gunicorn service is running
      systemd:
        daemon_reload: true
        enabled: true
        state: started
        name: "{{ gunicorn_service_name }}"
